#!/usr/bin/bash
TMP_DIR="/tmp/env_${UID}"; mkdir -p -- "$TMP_DIR"; chmod 700 -- "$TMP_DIR"
SSH_ENV="$TMP_DIR/ssh_env"; if [[ ! -f "$SSH_ENV" ]]; then /usr/bin/ssh-agent | sed "/^echo/d;s/;.*//" > "$SSH_ENV"; fi
chmod 600 -- "$SSH_ENV"
[[ -s "$SSH_ENV" ]] && IFS=$'\n' export $(<"$SSH_ENV")
unset TMP_DIR SSH_ENV
env -u QT_STYLE_OVERRIDE keepassxc "$@"

