#!/bin/bash
get_size() {
	mon="$(hyprctl monitors -j | jq -r --arg mon "$1" 'map(select(.name == $mon))[0]')"
	if [[ "$mon" == "null"  ]]; then
		return 1
	fi
	width="$(jq -r '.width' <<< "$mon")"
	height="$(jq -r '.height' <<< "$mon")"
	transform="$(jq -r '.transform' <<< "$mon")"
	if [[ "$transform" == 1 || "$transform" == 3 ]]; then
		echo "${height}x${width}"
	else
		echo "${width}x${height}"
	fi
}
convert() {
	val="$(get_size "$2")"
	if [[ -z "$val" ]]; then
		echo "Monitor $2 not found"
		return 1
	fi
	magick -density 300 "$1" -gravity center -resize "$val"^ -extent "$val" "$3" && echo "Converted $1 to $3 with size $val"
}

# change the images and monitors to your needs
convert ~/.wallpapers/1 HDMI-A-1 ~/.wallpapers/1-adjusted.png
convert ~/.wallpapers/2 DP-2     ~/.wallpapers/2-adjusted.png
convert ~/.wallpapers/3 DP-1     ~/.wallpapers/3-adjusted.png
convert ~/.wallpapers/4 eDP-1    ~/.wallpapers/4-adjusted.png

rewallpaper # update the wallpapers
