#!/bin/bash
function killswayidle() {
	killall -q swayidle -q
}
function disable-autolock() {
	killswayidle
}
function enable-autolock() {
	killswayidle
	swayidle -w timeout 60 ~/.bin/lock &
}
if [[ "$1" == "on" ]]; then
	enable-autolock
elif [[ "$1" == "off" ]]; then
	disable-autolock
else
	if pidof -sq swayidle; then
		disable-autolock
		notify-send "Disabled auto-lock" -a ""
	else
		enable-autolock
		notify-send "Enabled auto-lock" -a ""
	fi
fi
