#!/bin/bash
# Avoid race conditions by storing the address in a variable
ACTIVE="$(hyprctl activewindow -j)"
# Rofi crashes Hyprland when toggle floating
( jq -r .class<<<"$ACTIVE" | grep -qxFi Rofi ) || hyprctl dispatch togglefloating address:"$(jq -r .address<<<"$ACTIVE")"
